### ISSUE TITLE
IndexError: Pop from empty list

### ISSUE THREAD

**Issue by JordanShackelford** [vingtfranc/LoLAnalyzer#3]
data_1.csv stored for testing
data_2.csv stored for testing
data_3.csv stored for testing
Traceback (most recent call last):
  File "RunAll.py", line 55, in <module>
    DataShuffling.run(m, shuffling_files, keep_for_testing, cpu)
  File "C:\Users\Jordan\Desktop\leaguenn\DataShuffling.py", line 68, in run
    testing_file = preprocessed_files.pop(0)  # take data away for testing
IndexError: pop from empty list

I changed the end of DataShuffling.py to `m = Modes.ABR_TJMCS_Mode(['7.20'])` from 7.18 and 7.19, but this didn't fix the error.

**Comment by VRichardJP** [comment]
change `keep_for_testing = 7` in RunAll.py (to 1 for example). Since you don't have a lot of data, you may have trouble getting results (i would say you need at least 20 data files to see something). Think about downloading games from all the servers to get more data (API limitations are independant).
